to_do_2/list/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name = 'list'
urlpatterns = [
    
    path('', views.list, name='list'),
    path('<int:list_id>/', views.detail, name='detail'),
]

to_do_2/to_do_2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('list/', include('list.urls'))
]

to_do_2/list/models.py
from django.db import models

# Create your models here.
class List(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField
    pub_date = models.DateTimeField('date published')

    def __str__(self):
          return self.name

class ToDoItem(models.Model):
    list = models.ForeignKey(List, on_delete=models.CASCADE)
    text = models.CharField(max_length=250)
    description = models.TextField
    done = models.BooleanField(default=False)

    def __str__(self):
          return f"{self.text} {self.done}"

to_do_2/list/views.py
from typing import List

from django.http import HttpResponse

from django.shortcuts import get_object_or_404, render, HttpResponseRedirect

from .models import List, ToDoItem

from django.template import loader

from django.urls import reverse

# Create your views here.

def list(request):
    lists_list = List.objects.order_by('name')
    template = loader.get_template('list/list.html')
    context = {
        'lists_list': lists_list,
    }
    return HttpResponse(template.render(context, request))

def detail(request, list_id):
    list = get_object_or_404(List, pk=list_id)
    return render(request, 'list/detail.html', {'list': list})

def status_change(request, todoitem_id):
    todo = get_object_or_404(TodoItem, pk=todoitem_id)
    if todo.done == True:
        todo.done = False
    else:
        todo.done = True
    todo.save()
    return HttpResponseRedirect(reverse('list:detail'))

to_do_2/list/templates/list/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Liste</title>
</head>
<body>
    <h1>{{ list.name }}</h1>
        <ul>

        {% for item in list.todoitem_set.all %}


         
        
            {% if item.done == False %}
                <li><h3>{{ item.text }}</h3></li>

                   
                <button type="submit" class="badge rounded-pill bg-warning" method="post">als erledigt markieren</button>
                {% csrf_token %}
            {% endif %}
            {% if item.done == True %}
                <li><h4><del>{{ item.text }}</del></h4></li>

                
                <button type="submit" class="badge rounded-pill bg-successs" method="post">wieder aktivieren</button>
                {% csrf_token %}
            {% endif %}

     


            {% endfor %}
        </ul>
       

</body>
</html>

to_do_2/list/templates/list/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Übersicht</title>
</head>
<body>
    <h1>Listenauswahl</h1>

    {% if lists_list %}
    <ul>
    {% for list in lists_list %}
        <li><a href="{% url 'list:detail'  list.id %}">{{ list.name }}</a></li>
        
        
    {% endfor %}
    </ul>
{% else %}
    <p>No lists are available.</p>
{% endif %}
</body>
</html>