einkaufsliste/einkaufsliste/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ek_list/', include('ek_list.urls'))
]

einkaufsliste/ek_list/urls.py
from django.contrib import admin
from . import views
from django.urls import path

app_name = "ek_list"
urlpatterns = [
    path('', views.shops, name='shops'),
    path('<int:shop_id>/', views.list, name='list'),
    path('<int:product_id>/status_change', views.status_change, name="status_change"),
    path('new', views.new, name="new"),
    path('newshop', views.newshop, name="newshop"),
    path('<int:product_id>/delete_item', views.delete_item, name="delete_item"),
    path('<int:shop_id>/delete_shop', views.delete_shop, name="delete_shop"),
]

einkaufsliste/ek_list/models.py
from django.db import models

# Create your models here.

class Shop(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name}"



class Product(models.Model):
    status_choices = [
        ("D", "Done"),
        ("B", "Buy"),
        ("C", "Canceled")
    ]

    name = models.CharField(max_length=100)
    note = models.CharField(max_length=500)
    amount = models.IntegerField(default = 1)
    unit = models.CharField(max_length=15, default = "")
    price = models.FloatField(default = 0.00)
    status = models.CharField(max_length=1, choices=status_choices, default="B")
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} {self.shop} {self.status} {self.amount} {self.unit} {self.price}"

einkaufsliste/ek_list/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse

from .models import Shop, Product

# Create your views here.

def shops(request):
    shop_list = Shop.objects.order_by('name')
    template = loader.get_template('ek_list/shops.html')
    context = {
        'shop_list': shop_list,
    }
    return HttpResponse(template.render(context, request))

def list(request, shop_id):
    shop = get_object_or_404(Shop, pk=shop_id)
    return render(request, 'ek_list/list.html', {'shop': shop, 'status_choices' : Product.status_choices, 'shops' : Shop.objects.all()})


def status_change(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    product.status = request.POST["status"] 
    product.save()
    shop_id= product.shop.id
    return redirect('ek_list:list', product.shop.id)
    

def delete_item(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    get_object_or_404(Product, pk=product_id).delete()
    return redirect('ek_list:list', product.shop.id)

def delete_shop(request, shop_id):
    get_object_or_404(Shop, pk=shop_id).delete()
    return HttpResponseRedirect(reverse ('ek_list:shops'))



    
def new(request):
    name = request.POST["name"]
    note = request.POST["note"]
    amount = request.POST["amount"]
    unit = request.POST["unit"]
    price = request.POST["price"]
    status = request.POST["status"]
    shop = Shop.objects.get(pk=request.POST["shop"])

    print(name, note, amount, unit, price, status, shop)

    Product.objects.create(name=name,
                        note=note,
                        amount=amount,
                        unit=unit,
                        price=price,
                        status = status,
                        shop=shop)
    return HttpResponseRedirect(reverse('ek_list:shops'))
    

def newshop(request):
    name = request.POST["name"]


    print(name)

    Shop.objects.create(name=name)
    return HttpResponseRedirect(reverse('ek_list:shops'))

einkaufsliste/ek_list/templates/ek_list/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>{{shop.name}}</title>
</head>
<body>
    <h1>{{ shop.name }}</h1>
    <table class="table table-dark table-striped">
        <thead>
          <tr>
            <th scope="col">Amount</th>
            <th scope="col">Unit</th>
            <th scope="col">Product</th>
            <th scope="col">Price</th>
            <th scope="col">Note</th>
            <th scope="col">Status</th>
            <th scope="col">Change Status</th>
            <th scope="col">Delete Item</th>
          </tr>
        </thead>
        <tbody>
        {% for product in shop.product_set.all %}
            
                {% if product.status == "B" %}
                <tr>
                    <th scope="row">{{ product.amount }}</th>
                    <td>{{ product.unit }}</td>
                    <td>{{ product.name }}</td>
                    <td>{{ product.price }}</td>
                    <td>{{ product.note }}</td>
                    <td>needed</td>
                    <td>   
                        <form action="{% url 'ek_list:status_change' product.id %}" method="post">
                        {% csrf_token %}
                        <select name="status">
                          {% for item in product.status_choices %}
                          <option value="{{item.0}}">{{item.1}}</option>
                          {% endfor %}
                          </select>
                        <input type="submit" value="Change">
                      </form>
                    </td>
                    <td>
                      <form action="{% url 'ek_list:delete_item' product.id %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="Delete">
                    </td>
                </tr>
                {% endif %}

                {% if product.status == "D" %}
                <tr>
                    <th scope="row">{{ product.amount }}</th>
                    <td>{{ product.unit }}</td>
                    <td><del>{{ product.name }}</del></td>
                    <td>{{ product.price }}</td>
                    <td>{{ product.note }}</td>
                    <td>allready bought</td>
                    <td>   
                        <form action="{% url 'ek_list:status_change' product.id %}" method="post">
                        {% csrf_token %}
                        <select name="status">
                          {% for item in product.status_choices %}
                          <option value="{{item.0}}">{{item.1}}</option>
                          {% endfor %}
                          </select>
                        <input type="submit" value="Change">
                      </form>
                    </td>
                    <td>
                      <form action="{% url 'ek_list:delete_item' product.id %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="Delete">
                    </td>
                </tr>
                {% endif %}

                {% if product.status == "C" %}
                <tr class="table-secondary">
                    <th scope="row"><del></del>{{ product.amount }}</th>
                    <td><del>>{{ product.unit }}</del></td>
                    <td><del>{{ product.name }}</del></td>
                    <td><del>{{ product.price }}</del></td>
                    <td><del>{{ product.note }}</del></td>
                    <td>canceled</td>
                    <td>   
                        <form action="{% url 'ek_list:status_change' product.id %}" method="post">
                        {% csrf_token %}
                        <select name="status">
                          {% for item in product.status_choices %}
                          <option value="{{item.0}}">{{item.1}}</option>
                          {% endfor %}
                          </select>
                        <input type="submit" value="Change">
                      </form>
                    </td>
                    <td>
                      <form action="{% url 'ek_list:delete_item' product.id %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="Delete">
                    </td>
                </tr>
                {% endif %}
          
        {% endfor %}
        </tbody>
    </table>

      <h2>Create New Product</h2>
      
      <form action="{% url 'ek_list:new' %}" method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon3">Amount</span>
            <input type="text" name="amount" class="form-control" id="basic-url" aria-describedby="basic-addon3"><br>
            
            <span class="input-group-text" id="basic-addon3">Unit</span>
            <input type="text" name="unit" class="form-control" id="basic-url" aria-describedby="basic-addon3"><br>

            <span class="input-group-text" id="basic-addon3">Product</span>
            <input type="text" name="name" class="form-control" id="basic-url" aria-describedby="basic-addon3"><br>

            <span class="input-group-text" id="basic-addon3">Price</span>
            <input type="number" name="price" class="form-control" id="basic-url" aria-describedby="basic-addon3"><br>
            
            <span class="input-group-text" id="basic-addon3">Note</span>
            <input type="text" name="note" class="form-control" id="basic-url" aria-describedby="basic-addon3"><br>
        </div>
        <label>Status</label>
        <select name="status">
          {% for item in status_choices %}
            <option value="{{item.0}}">{{item.1}}</option>
          {% endfor %}
        </select><br>
        <label>Shop</label>
        <select name="shop">
          {% for shop in shops %}
          <option value="{{shop.id}}">{{shop}}</option>
          {% endfor %}
        </select><br>
        <input type="submit" value="Create">
      </form>
    
</body>
</html>

einkaufsliste/ek_list/templates/ek_list/shops.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Shops</title>
</head>
<body>
    <h1>Choose Shop</h1>

    {% if shop_list %}
    <ul>
    {% for shop in shop_list %}
        <li><a href="{% url 'ek_list:list'  shop.id %}">{{ shop.name }}</a></li>
        <form action="{% url 'ek_list:delete_shop' shop.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Delete Shop">
        
        
    {% endfor %}
    </ul>
{% else %}
    <p>No lists are available.</p>
{% endif %}

<h2>Create New Shop</h2>
<form action="{% url 'ek_list:newshop' %}" method="post">
    {% csrf_token %}
    <label>Name</label><input type="text" name="name">
    <input type="submit" value="Create">
  </form>

</body>
</html>