newproject_d4/highscore/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'highscore'
urlpatterns = [
   path('', views.index, name='index'),
   path('leaderboard/<int:pk>/', views.leaderboard, name='leaderboard'),
   path('new_board/', views.new_board, name='new_board'),
   path('score_entry/<int:pk>/', views.score_entry, name='score_entry'),
   path('new_entry/<int:pk>/', views.new_entry, name='new_entry'),
   path('save_board/', views.save_board, name='save_board'),
   path('api/v1/boards/<int:board_id>/', views.api_v1_boards, name='api_v1_boards'),
]

newproject_d4/newproject_d4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('highscore/', include('highscore.urls'))
]

newproject_d4/highscore/models.py
from django.db import models

# Create your models here.
class Leaderboard(models.Model):
    submit_pw = models.CharField(max_length=50)
    edit_pw = models.CharField(max_length=50)
    date_created = models.DateTimeField(auto_now_add=True)
    game_title = models.CharField(max_length=75)
    game_subtitle = models.CharField(max_length=150, blank=True, null=True)
    note = models.TextField(blank=True, null=True)
    game_url = models.URLField(blank=True, null=True)
    
    def __str__(self):
        return f"{self.game_title} {self.game_subtitle} {self.note}"

class Score(models.Model):
    SUBMISSION_TYPES = (
        ('A', 'API'),
        ('M', 'manually'),
    )
    submission_type = models.CharField(max_length=1, choices=SUBMISSION_TYPES)
    player_name = models.CharField(max_length=50, default='Anonymous')
    score = models.IntegerField(blank=True, default=0)
    playtime = models.CharField(max_length= 30, default="00:00:00")
    leaderboard = models.ForeignKey(Leaderboard, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    #additional_data = models.JSONField(encoder=None, decoder=None, blank=True, null=True)
    additional_data = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['-score', 'playtime']

    def __str__(self):
        return f"{self.player_name} {self.leaderboard}"
        

newproject_d4/highscore/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, redirect
from . models import Leaderboard, Score
from django.urls import reverse
import json
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
# Create your views here.

def index(request):
    leaderboards = Leaderboard.objects.order_by('date_created')
    context = {
        'leaderboards':leaderboards
    }
    return render (request, 'highscore/index.html', context)

def leaderboard(request, pk):
    board = Leaderboard.objects.get(id=pk)
    scores = Score.objects.filter(leaderboard_id=pk)[:10]
    context = {
        'board': board,
        'scores':scores
    }
    return render (request, 'highscore/board.html', context)

def score_entry(request, pk):
    board = Leaderboard.objects.get(id=pk)
    context = {
        'board': board
    }
    return render(request, 'highscore/score_entry.html', context)

def new_entry(request, pk):
    player_name = request.POST["player_name"]
    score = request.POST["score"]
    if score == "":
        score = 0
    playtime = request.POST["playtime"]
    leaderboard = Leaderboard.objects.get(id=pk)
    Score.objects.create(player_name=player_name,
    score=score,
    playtime=playtime,
    submission_type = 'M',
    leaderboard=leaderboard)
    return redirect('highscore:leaderboard', pk)
    return HttpResponseRedirect(reverse('leaderboard/', pk))


def new_board(request):
    return render(request, 'highscore/new_board.html')

def save_board(request):
   # game_title = request.POST["game_title"]
  #  game_subtitle = request.POST["game_subtitle"]
  #  note = request.POST["note"]
  #  game_url = request.POST["game_url"]
   # edit_pw = request.POST["edit_pw"]
  #  submit_pw = request.POST["submit_pw"]
    

   # Leaderboard.objects.create(game_title=game_title,
   #             game_subtitle=game_subtitle,
   #             note=note,
            
   #             game_url=game_url,
   #             edit_pw=edit_pw,
   #             submit_pw=submit_pw)
    leaderboard = Leaderboard()
    
    leaderboard.game_title = request.POST["game_title"]
    leaderboard.game_subtitle = request.POST["game_subtitle"]
    leaderboard.note = request.POST["note"]
    leaderboard.game_url = request.POST["game_url"]
    leaderboard.edit_pw = request.POST["edit_pw"]
    leaderboard.submit_pw = request.POST["submit_pw"]
    #leaderboard.
    leaderboard.save()
    return redirect('highscore:index')


  



@csrf_exempt
def api_v1_boards(request, board_id, password):
    board = get_object_or_404(Leaderboard, id=board_id, password=password)
    if request.POST:
        # A new score is submitted
        payload = json.loads(request.body)
        score = Score()
        score.board = board
        if "name" in payload:
            score.player_name = payload["name"]
        if "time" in payload:
            score.playtime = payload["time"]
        if "score" in payload:
            score.score = payload["score"]
        score.submission_type = "A"
        score.save()
        response = {"result": "ok"}
        return JsonResponse(response)
    else:
        # GET request, we return the current highscores
        response = {
            "title": board.game_title,
            "description": board.game_subtitle,
            "created": board.date_created,
            "scores": [],
                }
        for score in board:
            response["scores"].append({
                    "name": score.player_name,
                    "score": score.score,
                    "time": score.playtime,
                    "created": score.date_created,
                })
        return JsonResponse(response)

newproject_d4/highscore/templates/highscore/board.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ board.game_title }}</title>
</head>
<body>
    <h1>{{board.game_title}}-Highscore</h1>
    <strong>API Link:</strong> <a href="/boards/api_v1_boards/{{ board.id }}">Right click to copy!</a>
    <ol>
    {% for score in scores %}
        
            <li> <strong>Name: </strong>{{score.player_name}}  <br>
                <strong>Score: </strong> {{score.score}} <br>
                <strong>Time:</strong> {% if score.playtime %}  {{score.playtime}}  {% endif%}</li>
            <hr>
        
    {% endfor %}
    </ol>
    <a href="/highscore/score_entry/{{board.id}}">Neuen Score (manuel) eintragen</a>
</body>
</html>

newproject_d4/highscore/templates/highscore/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
</head>
<body>

    <h1>Spiele/Leaderboards</h1>
    <div>
        <table>
            <tr>
                <th>Title</th>
                <th>Version</th>
                <th>Try Game</th>
            </tr>
        
    
            {% for board in leaderboards %}
            <tr>
                <td><a href="/highscore/leaderboard/{{board.id}}">{{board.game_title}}</a></td>
                <td>{{board.game_subtitle}}</td>
                <td><a href="{{board.game_url}}">Play</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>>
    <a href="/highscore/new_board/">Neues Leaderboard anlegen</a>
</body>
</html>

newproject_d4/highscore/templates/highscore/new_board.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Neues Board anlegen</title>
</head>
<body>
    <form action="{% url 'highscore:save_board'%}" method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon3">Name des Spiels</span>
            <input type="text" name="game_title" class="form-control" id="basic-url" aria-describedby="basic-addon3"><br>
            
            <span class="input-group-text" id="basic-addon3">Untertitel oder Version (optional)</span>
            <input type="text" name="game_subtitle" class="form-control" id="basic-url" aria-describedby="basic-addon3"><br>

            <span class="input-group-text" id="basic-addon3">Bemerkungen (optional)</span>
            <input type="text" name="note" class="form-control" id="basic-url" aria-describedby="basic-addon3"><br>

            <span class="input-group-text" id="basic-addon3">url des spiels (optional)</span>
            <input type="text" name="game_url" class="form-control" id="basic-url" aria-describedby="basic-addon3"><br>

            <span class="input-group-text" id="basic-addon3">Passwort zum editieren des Boards</span>
            <input type="password" name="edit_pw" class="form-control" id="basic-url" aria-describedby="basic-addon3"><br>

            <span class="input-group-text" id="basic-addon3">Passwort zum eintragen in das Board</span>
            <input type="password" name="submit_pw" class="form-control" id="basic-url" aria-describedby="basic-addon3"><br>

        </div>
        <input type="submit" value="Create">
    </form>
</body>
</html>

newproject_d4/highscore/templates/highscore/score_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'highscore:new_entry' board.id %}" method="post"> 
        {% csrf_token %}
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon3">Name</span>
            <input type="text" name="player_name" placeholder="Name" class="form-control" id="basic-url" aria-describedby="basic-addon3"><br>
            
            <span class="input-group-text" id="basic-addon3">Score</span>
            <input type="text" name="score"  placeholder="Score" class="form-control" id="basic-url" aria-describedby="basic-addon3"><br>

            <span class="input-group-text" id="basic-addon3">Spielzeit(optional -hh:mm:ss)</span>
            <input type="text" name="playtime"  placeholder="Time"class="form-control" id="basic-url" aria-describedby="basic-addon3"><br>
        </div>
        <input type="submit" value="Create">
    </form>
</body>
</html>